name: Generate Stats

on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Stats
        run: |
          chmod +x repo_status.sh
          ./repo_status.sh

      - name: Commit and Push Changes
        run: |
          git add results.md
          git commit -m "Updating stats"
          git push