name: Generate Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Run at 00:00 every day
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Stats
        run: |
          chmod +x repo_status.sh
          ./repo_status.sh java
          ./repo_status.sh nodejs
          ./repo_status.sh python
          cat java-results.md nodejs-results.md python-results.md>README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'Deepankar'
          git config --global user.email 'ddixit14@users.noreply.github.com'
          git commit -am "Update Repo Status"
          git push