name: Generate Node Stats

on:
  schedule:
     - cron: '0 5 * * *' # Run the java script at 1 AM
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Stats
        run: |
          chmod +x repo_status.sh
          ./repo_status.sh nodejs

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'Deepankar'
          git config --global user.email 'ddixit14@users.noreply.github.com'
          git commit -am "Update Repo Status"
          git push
